In [16]:
import numpy as np
import seaborn as sb
import pandas as pd

In [17]:
l=[1,4,5,6,7]

In [18]:
l

[1, 4, 5, 6, 7]

In [19]:
2*l #double time printing list

[1, 4, 5, 6, 7, 1, 4, 5, 6, 7]

In [20]:
b=np.array(l)

In [21]:
2*b

array([ 2,  8, 10, 12, 14])

In [32]:
x=np.array([[1,2,3,4,5],[7,6,8,9,2]])

In [33]:
x.shape

(2, 5)

In [34]:
x.itemsize

4

In [35]:
x.reshape(2*5)

array([1, 2, 3, 4, 5, 7, 6, 8, 9, 2])

In [37]:
x=np.array([[1,2,3],[7,6,8],[2,4,3],[3,4,5]])

In [38]:
x.shape

(4, 3)

In [39]:
x.reshape(3,4)

array([[1, 2, 3, 7],
       [6, 8, 2, 4],
       [3, 3, 4, 5]])

In [40]:
x

array([[1, 2, 3],
       [7, 6, 8],
       [2, 4, 3],
       [3, 4, 5]])

In [56]:
x[0,1:3]

array([2, 3])

In [58]:
x[1:3,1:3]  #[row slize,column size]

array([[6, 8],
       [4, 3]])

In [59]:
np.sqrt(x) #sruareroot for particular elements in array

array([[1.        , 1.41421356, 1.73205081],
       [2.64575131, 2.44948974, 2.82842712],
       [1.41421356, 2.        , 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [60]:
np.cbrt(x)

array([[1.        , 1.25992105, 1.44224957],
       [1.91293118, 1.81712059, 2.        ],
       [1.25992105, 1.58740105, 1.44224957],
       [1.44224957, 1.58740105, 1.70997595]])

In [61]:
np.std(x)

2.041241452319315

In [62]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])

In [63]:
np.hstack((x,y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [64]:
np.vstack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])